import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const brand = process.env.BRAND;

if (!brand) {
  console.error('Error: BRAND environment variable is required.');
  console.error('  Example: BRAND=roofrxservices node scripts/apply-brand.mjs');
  process.exit(1);
}

const brandDir = join(root, 'brands', brand);
if (!existsSync(brandDir)) {
  console.error(`Error: Unknown brand "${brand}". Directory not found: brands/${brand}`);
  process.exit(1);
}

const theme = JSON.parse(readFileSync(join(brandDir, 'theme.json'), 'utf-8'));

const brandThemeCSS = `/* Generated by scripts/apply-brand.mjs — do not edit manually */
@theme {
  --color-roof-700: ${theme.colors['roof-700']};
  --color-roof-800: ${theme.colors['roof-800']};
  --color-roof-900: ${theme.colors['roof-900']};
  --color-roof-accent: ${theme.colors['roof-accent']};
  --color-roof-accent-hover: ${theme.colors['roof-accent-hover']};

  --font-sans: ${theme.fonts.sans};
  --font-display: ${theme.fonts.display};
}
`;

writeFileSync(join(root, 'css', 'brand-theme.css'), brandThemeCSS);
console.log(`[apply-brand] css/brand-theme.css written`);

copyFileSync(join(brandDir, 'site-settings.json'), join(root, 'content', 'site-settings.json'));
console.log(`[apply-brand] content/site-settings.json updated`);

console.log(`[apply-brand] Brand "${brand}" applied.`);
